version: "1.0"
stages:
    - "clone"
    - "build"
    - "deploy"
steps:
    main_clone:
        type: "git-clone"
        description: "Cloning main repository..."
        repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
        revision: "${{CF_REVISION}}"
        stage: "clone"
    build:
        title: "Building Docker Image"
        type: "build"
        image_name: "surat-dreams-user-management"
        tag: "${{CF_BRANCH}}-${{CF_REVISION}}"
        dockerfile: "Dockerfile"
        stage: "build"
        registry: "${{ecr}}"
    deploy:
        title: Running Deploy Script
        type: deploy
        kind: kubernetes
        cluster: "${{cluster}}"
        namespace: "${{namespace}}"
        service: surat-dreams-user-management
        candidate:
            image: "${{build}}"
            registry: "${{ecr}}"
        stage: "deploy"
